# Generated by Django 2.1.1 on 2018-11-17 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20181114_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examrecord',
            old_name='questions',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='examrecord',
            old_name='choices',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='score',
            field=models.CharField(default=datetime.datetime(2018, 11, 17, 16, 26, 9, 71335, tzinfo=utc), max_length=225),
            preserve_default=False,
        ),
    ]
